#!/bin/bash

sed -i '/hint_type/c\   \"hint_type\" : \"desktop\",' /opt/jade/application-settings.json

sleep 3s

FILE=/tmp/webdad-first-run.lock  
   
if [ -f $FILE ]; then

   rm $FILE && exit 0;

else 

  if pgrep -x "jade-dashboard" > /dev/null; 
  then     echo "Running"; 
  else     notify-send -i /opt/jade/img/jade-logo.svg "Desktop Loading" & /usr/bin/jade-desktop;
  fi & 

  if pgrep -x "compton" > /dev/null; 
  then     echo "Running"; 
  else     compton --config /usr/share/themes/Adapta-Maia/openbox-3/compton.conf;
  fi &
 
  if pgrep -x "steam" > /dev/null; 
  then     pkill steam; 
  fi &

  if pgrep -x "kodi" > /dev/null; 
  then     pkill kodi; 
  fi  &

  if pgrep -x "cairo-dock" > /dev/null; 
  then     echo "Running"; 
  else     cairo-dock -o -d /etc/webdad/cairo-dock;
  fi &

  if pgrep -x "msm_notifier" > /dev/null; 
  then     echo "Running"; 
  else     msm_notifier;
  fi &

  if pgrep -x "nm-applet" > /dev/null; 
  then     echo "Running"; 
  else     nm-applet;
  fi &

  if pgrep -x "pamac-tray" > /dev/null; 
  then     echo "Running"; 
  else     pamac-tray;
  fi    

fi
