#!/bin/bash

if pgrep -x "compton" > /dev/null; 
then     echo "Running"; 
else     compton --config /usr/share/themes/Adapta-Maia/openbox-3/compton.conf;
fi &

notify-send -i /etc/webdad/jwm/workspaces/internet-browsing-mode.jpg "Internet Browsing Mode Loading" &

if pgrep -x "jade-dashboard" > /dev/null; 
then     pkill jade-dashboard; 
fi &

if pgrep -x "kodi" > /dev/null; 
then     pkill kodi; 
fi &

if pgrep -x "steam" > /dev/null; 
then     pkill steam; 
fi &

if pgrep -x "msm_notifier" > /dev/null; 
then     pkill msm_notifier; 
fi &


if pgrep -x "pamac-tray" > /dev/null; 
then     pkill pamac-tray; 
fi &

if pgrep -x "cairo-dock" > /dev/null; 
then     echo "Running"; 
else     cairo-dock -o -d /etc/webdad/cairo-dock;
fi &

if pgrep -x "$JADE_BROWSER" > /dev/null; 
then     echo "Running"; 
else     $JADE_BROWSER;
fi
