#!/bin/bash

notify-send -i /usr/share/icons/Paper/512x512/apps/kodi.png "Media Center Loading" &

if pgrep -x "steam" > /dev/null; 
then     pkill steam; 
fi &

if pgrep -x "$JADE_BROWSER" > /dev/null; 
then     pkill $JADE_BROWSER; 
fi &

if pgrep -x "$JADE_TERMINAL" > /dev/null; 
then     pkill $JADE_TERMINAL; 
fi &

if pgrep -x "jade-dashboard" > /dev/null; 
then     pkill jade-dashboard; 
fi &

if pgrep -x "cairo-dock" > /dev/null; 
then     pkill cairo-dock; 
fi &

if pgrep -x "msm_notifier" > /dev/null; 
then     pkill msm_notifier; 
fi &

if pgrep -x "nm-applet" > /dev/null; 
then     pkill nm-applet; 
fi &

if pgrep -x "pamac-tray" > /dev/null; 
then     pkill pamac-tray; 
fi &

if pgrep -x "kodi" > /dev/null; 
then     echo "Running"; 
else     
  kodi &
  if pgrep -x "compton" > /dev/null; 
  then     pkill compton; 
  fi
fi
