#!/bin/bash

if pgrep -x "compton" > /dev/null; 
then     echo "Running"; 
else     compton --config /usr/share/themes/Adapta-Maia/openbox-3/compton.conf;
fi &

notify-send -i /usr/share/pixmaps/hyper.png "Terminal Mode Loading" &

if pgrep -x "jade-dashboard" > /dev/null; 
then     pkill jade-dashboard; 
fi &

if pgrep -x "kodi" > /dev/null; 
then     pkill kodi; 
fi &

if pgrep -x "steam" > /dev/null; 
then     pkill steam; 
fi &

if pgrep -x "nm-applet" > /dev/null; 
then     pkill nm-applet; 
fi &

if pgrep -x "cairo-dock" > /dev/null; 
then     echo "Running"; 
else     cairo-dock -o -d /etc/webdad/cairo-dock;
fi &

if pgrep -x "$JADE_TERMINAL" > /dev/null; 
then     echo "Running";
else     $JADE_TERMINAL; 
fi 

